export const DASHBOARD_LIMITS = {
  TOP_OPPORTUNITIES: 10,
  RECENT_TASKS: 5,
  TOP_GAPS: 3,
  FOCUS_TASKS: 10,
  ACCOUNT_GAPS_DISPLAY: 5,
  TERRITORY_RANKING: 4,
  QUICK_WINS: 3,
} as const;

export const DEFAULT_VALUES = {
  BASELINE_REVENUE: 50000,
  SHARE_RATE: "0.10",
  CATEGORY_COUNT: 0,
  OPPORTUNITY_SCORE: 0,
  FALLBACK_REVENUE: 100000,
  QUICK_WIN_REVENUE: 5000,
} as const;

export const SCORING = {
  NEAR_ICP_THRESHOLD: 20,
  DEFAULT_GAP_PERCENTAGE: 30,
  MAX_SCORE: 100,
} as const;

export const SLICE_LIMITS = {
  TOP_3: 3,
  TOP_5: 5,
  TOP_10: 10,
  CATEGORY_SUGGESTIONS: 2,
} as const;

export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 50,
  MAX_LIMIT: 100,
} as const;
